security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # ...
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        main:
            # ...
            form_login:
                provider: app_user_provider
                # ...
