app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
app_connexion:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
app_inscription:
    path: lucky/inscription
    controller: App\Controller\InscriptionController::number
app_profil:
    path: lucky/profil
    controller: App\Controller\ProfilController::number

app_home:
    path: /home
    controller: App\Controller\HomeController::number